// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://raqrbnpvnxoioywabvao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhcXJibnB2bnhvaW95d2FidmFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5ODk2NjksImV4cCI6MjA2MjU2NTY2OX0.amxHazX8bjDvu5bWaUzwtHKc7bLo2TImOvWo6bQbNC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);